# Generated by Django 4.2.11 on 2026-05-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_tipoinstrumento_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='audio_sample',
            field=models.FileField(blank=True, null=True, upload_to='instrumentos/audio/'),
        ),
    ]
