# Generated by Django 4.2.11 on 2026-05-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_instrumento_audio_sample_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='origen',
            field=models.CharField(blank=True, help_text='País o región de origen del instrumento', max_length=100),
        ),
    ]
